name: gym_counter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0

  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^18.0.0
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.0
  flutter_ringtone_player: ^4.0.0+3
  http: ^1.2.2
  image: ^4.3.0
  flutter_timezone: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
    - assets/sounds/output.mp3
  uses-material-design: true
